import PDFDocument from 'pdfkit';
import { FinancialAnalysis } from '@shared/schema';

export async function generateFinancialReport(analysis: FinancialAnalysis): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const buffers: Buffer[] = [];
      
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });
      
      // Header
      doc.fontSize(24).text('Balancify AI - Financial Analysis Report', { align: 'center' });
      doc.moveDown();
      
      // Spending Breakdown
      doc.fontSize(18).text('Spending Breakdown');
      doc.moveDown();
      
      const spending = JSON.parse(analysis.spendingBreakdown as string);
      Object.entries(spending).forEach(([category, amount]) => {
        doc.fontSize(12).text(`${category}: ₹${amount}`, { indent: 20 });
      });
      
      doc.moveDown();
      
      // Needs vs Wants Analysis
      doc.fontSize(18).text('Needs vs Wants Analysis');
      doc.moveDown();
      
      const needsWants = JSON.parse(analysis.needsWantsAnalysis as string);
      doc.fontSize(12).text(`Needs: ${needsWants.needsPercentage}%`, { indent: 20 });
      doc.fontSize(12).text(`Wants: ${needsWants.wantsPercentage}%`, { indent: 20 });
      
      doc.moveDown();
      
      // AI Insights
      doc.fontSize(18).text('AI Insights');
      doc.moveDown();
      doc.fontSize(12).text(analysis.aiInsights, { indent: 20 });
      
      doc.moveDown();
      
      // Recommendations
      doc.fontSize(18).text('Recommendations');
      doc.moveDown();
      
      const recommendations = JSON.parse(analysis.recommendations as string);
      doc.fontSize(14).text('Immediate Actions:', { indent: 20 });
      recommendations.immediate?.forEach((rec: string) => {
        doc.fontSize(12).text(`• ${rec}`, { indent: 40 });
      });
      
      doc.moveDown();
      doc.fontSize(14).text('Short-term Goals:', { indent: 20 });
      recommendations.shortTerm?.forEach((rec: string) => {
        doc.fontSize(12).text(`• ${rec}`, { indent: 40 });
      });
      
      doc.moveDown();
      doc.fontSize(14).text('Long-term Strategy:', { indent: 20 });
      recommendations.longTerm?.forEach((rec: string) => {
        doc.fontSize(12).text(`• ${rec}`, { indent: 40 });
      });
      
      // Footer
      doc.moveDown(2);
      doc.fontSize(10).text('Generated by Balancify AI', { align: 'center' });
      doc.text(`Report Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
      
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
